WARNING:2023-04-05 10:44:37,333:app:Starting the db connection to display all guests in the list
ERROR:2023-04-05 10:44:37,590:app:Error occurred: column "details" does not exist
LINE 1: SELECT * FROM hotel WHERE details[0] = 'Naruto';
                                  ^
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 107, in search_guests
    cur.execute(show_query, (name, ))
psycopg2.errors.UndefinedColumn: column "details" does not exist
LINE 1: SELECT * FROM hotel WHERE details[0] = 'Naruto';
                                  ^

ERROR:2023-04-05 10:44:37,590:app:Error occurred: column "details" does not exist
LINE 1: SELECT * FROM hotel WHERE details[0] = 'Naruto';
                                  ^
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 107, in search_guests
    cur.execute(show_query, (name, ))
psycopg2.errors.UndefinedColumn: column "details" does not exist
LINE 1: SELECT * FROM hotel WHERE details[0] = 'Naruto';
                                  ^

WARNING:2023-04-05 10:44:37,593:app:Hence details displayed, closing the connection
WARNING:2023-04-05 10:44:37,593:app:Hence details displayed, closing the connection
WARNING:2023-04-05 10:44:37,593:app:Hence details displayed, closing the connection
ERROR:2023-04-05 10:44:37,593:app:Exception on /search/Naruto [GET]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 107, in search_guests
    cur.execute(show_query, (name, ))
psycopg2.errors.UndefinedColumn: column "details" does not exist
LINE 1: SELECT * FROM hotel WHERE details[0] = 'Naruto';
                                  ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 115, in search_guests
    return jsonify({"message": error})
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type UndefinedColumn is not JSON serializable
ERROR:2023-04-05 10:44:37,593:app:Exception on /search/Naruto [GET]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 107, in search_guests
    cur.execute(show_query, (name, ))
psycopg2.errors.UndefinedColumn: column "details" does not exist
LINE 1: SELECT * FROM hotel WHERE details[0] = 'Naruto';
                                  ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 115, in search_guests
    return jsonify({"message": error})
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type UndefinedColumn is not JSON serializable
ERROR:2023-04-05 10:44:37,593:app:Exception on /search/Naruto [GET]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 107, in search_guests
    cur.execute(show_query, (name, ))
psycopg2.errors.UndefinedColumn: column "details" does not exist
LINE 1: SELECT * FROM hotel WHERE details[0] = 'Naruto';
                                  ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 115, in search_guests
    return jsonify({"message": error})
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type UndefinedColumn is not JSON serializable
WARNING:2023-04-05 10:45:15,465:app:Starting the db connection to display all guests in the list
ERROR:2023-04-05 10:45:15,685:app:Error occurred: cannot subscript type details because it is not an array
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 107, in search_guests
    cur.execute(show_query, (name, ))
psycopg2.errors.DatatypeMismatch: cannot subscript type details because it is not an array

ERROR:2023-04-05 10:45:15,685:app:Error occurred: cannot subscript type details because it is not an array
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 107, in search_guests
    cur.execute(show_query, (name, ))
psycopg2.errors.DatatypeMismatch: cannot subscript type details because it is not an array

WARNING:2023-04-05 10:45:15,688:app:Hence details displayed, closing the connection
WARNING:2023-04-05 10:45:15,688:app:Hence details displayed, closing the connection
WARNING:2023-04-05 10:45:15,688:app:Hence details displayed, closing the connection
ERROR:2023-04-05 10:45:15,688:app:Exception on /search/Naruto [GET]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 107, in search_guests
    cur.execute(show_query, (name, ))
psycopg2.errors.DatatypeMismatch: cannot subscript type details because it is not an array


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 115, in search_guests
    return jsonify({"message": error})
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type DatatypeMismatch is not JSON serializable
ERROR:2023-04-05 10:45:15,688:app:Exception on /search/Naruto [GET]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 107, in search_guests
    cur.execute(show_query, (name, ))
psycopg2.errors.DatatypeMismatch: cannot subscript type details because it is not an array


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 115, in search_guests
    return jsonify({"message": error})
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type DatatypeMismatch is not JSON serializable
ERROR:2023-04-05 10:45:15,688:app:Exception on /search/Naruto [GET]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 107, in search_guests
    cur.execute(show_query, (name, ))
psycopg2.errors.DatatypeMismatch: cannot subscript type details because it is not an array


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 115, in search_guests
    return jsonify({"message": error})
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type DatatypeMismatch is not JSON serializable
WARNING:2023-04-05 10:48:27,829:app:Starting the db connection to display all guests in the list
ERROR:2023-04-05 10:48:28,074:app:Error occurred: cannot subscript type details because it is not an array
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, value)
psycopg2.errors.DatatypeMismatch: cannot subscript type details because it is not an array

ERROR:2023-04-05 10:48:28,074:app:Error occurred: cannot subscript type details because it is not an array
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, value)
psycopg2.errors.DatatypeMismatch: cannot subscript type details because it is not an array

WARNING:2023-04-05 10:48:28,077:app:Hence details displayed, closing the connection
WARNING:2023-04-05 10:48:28,077:app:Hence details displayed, closing the connection
WARNING:2023-04-05 10:48:28,077:app:Hence details displayed, closing the connection
ERROR:2023-04-05 10:48:28,077:app:Exception on /search/Naruto [GET]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, value)
psycopg2.errors.DatatypeMismatch: cannot subscript type details because it is not an array


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 118, in search_guests
    return jsonify({"message": error})
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type DatatypeMismatch is not JSON serializable
ERROR:2023-04-05 10:48:28,077:app:Exception on /search/Naruto [GET]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, value)
psycopg2.errors.DatatypeMismatch: cannot subscript type details because it is not an array


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 118, in search_guests
    return jsonify({"message": error})
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type DatatypeMismatch is not JSON serializable
ERROR:2023-04-05 10:48:28,077:app:Exception on /search/Naruto [GET]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, value)
psycopg2.errors.DatatypeMismatch: cannot subscript type details because it is not an array


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 118, in search_guests
    return jsonify({"message": error})
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type DatatypeMismatch is not JSON serializable
WARNING:2023-04-05 10:48:48,066:app:Starting the db connection to display all guests in the list
ERROR:2023-04-05 10:48:48,067:app:Error occurred: not all arguments converted during string formatting
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, name)
TypeError: not all arguments converted during string formatting
ERROR:2023-04-05 10:48:48,067:app:Error occurred: not all arguments converted during string formatting
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, name)
TypeError: not all arguments converted during string formatting
WARNING:2023-04-05 10:48:48,070:app:Hence details displayed, closing the connection
WARNING:2023-04-05 10:48:48,070:app:Hence details displayed, closing the connection
WARNING:2023-04-05 10:48:48,070:app:Hence details displayed, closing the connection
ERROR:2023-04-05 10:48:48,071:app:Exception on /search/Naruto [GET]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, name)
TypeError: not all arguments converted during string formatting

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 118, in search_guests
    return jsonify({"message": error})
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type TypeError is not JSON serializable
ERROR:2023-04-05 10:48:48,071:app:Exception on /search/Naruto [GET]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, name)
TypeError: not all arguments converted during string formatting

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 118, in search_guests
    return jsonify({"message": error})
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type TypeError is not JSON serializable
ERROR:2023-04-05 10:48:48,071:app:Exception on /search/Naruto [GET]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, name)
TypeError: not all arguments converted during string formatting

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 118, in search_guests
    return jsonify({"message": error})
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type TypeError is not JSON serializable
WARNING:2023-04-05 10:49:16,791:app:Starting the db connection to display all guests in the list
ERROR:2023-04-05 10:49:17,314:app:Error occurred: cannot subscript type details because it is not an array
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, value)
psycopg2.errors.DatatypeMismatch: cannot subscript type details because it is not an array

ERROR:2023-04-05 10:49:17,314:app:Error occurred: cannot subscript type details because it is not an array
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, value)
psycopg2.errors.DatatypeMismatch: cannot subscript type details because it is not an array

WARNING:2023-04-05 10:49:17,317:app:Hence details displayed, closing the connection
WARNING:2023-04-05 10:49:17,317:app:Hence details displayed, closing the connection
WARNING:2023-04-05 10:49:17,317:app:Hence details displayed, closing the connection
ERROR:2023-04-05 10:49:17,317:app:Exception on /search/Naruto [GET]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, value)
psycopg2.errors.DatatypeMismatch: cannot subscript type details because it is not an array


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 118, in search_guests
    return jsonify({"message": error})
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type DatatypeMismatch is not JSON serializable
ERROR:2023-04-05 10:49:17,317:app:Exception on /search/Naruto [GET]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, value)
psycopg2.errors.DatatypeMismatch: cannot subscript type details because it is not an array


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 118, in search_guests
    return jsonify({"message": error})
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type DatatypeMismatch is not JSON serializable
ERROR:2023-04-05 10:49:17,317:app:Exception on /search/Naruto [GET]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, value)
psycopg2.errors.DatatypeMismatch: cannot subscript type details because it is not an array


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 118, in search_guests
    return jsonify({"message": error})
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type DatatypeMismatch is not JSON serializable
WARNING:2023-04-05 10:50:15,944:app:Starting the db connection to display all guests in the list
ERROR:2023-04-05 10:50:16,161:app:Error occurred: cannot subscript type details because it is not an array
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, value)
psycopg2.errors.DatatypeMismatch: cannot subscript type details because it is not an array

ERROR:2023-04-05 10:50:16,161:app:Error occurred: cannot subscript type details because it is not an array
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, value)
psycopg2.errors.DatatypeMismatch: cannot subscript type details because it is not an array

WARNING:2023-04-05 10:50:16,164:app:Hence details displayed, closing the connection
WARNING:2023-04-05 10:50:16,164:app:Hence details displayed, closing the connection
WARNING:2023-04-05 10:50:16,164:app:Hence details displayed, closing the connection
ERROR:2023-04-05 10:50:16,164:app:Exception on /search/Naruto [GET]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, value)
psycopg2.errors.DatatypeMismatch: cannot subscript type details because it is not an array


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 118, in search_guests
    return jsonify({"message": error})
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type DatatypeMismatch is not JSON serializable
ERROR:2023-04-05 10:50:16,164:app:Exception on /search/Naruto [GET]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, value)
psycopg2.errors.DatatypeMismatch: cannot subscript type details because it is not an array


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 118, in search_guests
    return jsonify({"message": error})
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type DatatypeMismatch is not JSON serializable
ERROR:2023-04-05 10:50:16,164:app:Exception on /search/Naruto [GET]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, value)
psycopg2.errors.DatatypeMismatch: cannot subscript type details because it is not an array


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 118, in search_guests
    return jsonify({"message": error})
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type DatatypeMismatch is not JSON serializable
WARNING:2023-04-05 10:51:31,150:app:Starting the db connection to display all guests in the list
ERROR:2023-04-05 10:51:31,415:app:Error occurred: operator does not exist: details ->> unknown
LINE 1: SELECT * FROM hotel WHERE guest_details ->> 'name' = 'Naruto...
                                                ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, value)
psycopg2.errors.UndefinedFunction: operator does not exist: details ->> unknown
LINE 1: SELECT * FROM hotel WHERE guest_details ->> 'name' = 'Naruto...
                                                ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

ERROR:2023-04-05 10:51:31,415:app:Error occurred: operator does not exist: details ->> unknown
LINE 1: SELECT * FROM hotel WHERE guest_details ->> 'name' = 'Naruto...
                                                ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, value)
psycopg2.errors.UndefinedFunction: operator does not exist: details ->> unknown
LINE 1: SELECT * FROM hotel WHERE guest_details ->> 'name' = 'Naruto...
                                                ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

WARNING:2023-04-05 10:51:31,418:app:Hence details displayed, closing the connection
WARNING:2023-04-05 10:51:31,418:app:Hence details displayed, closing the connection
WARNING:2023-04-05 10:51:31,418:app:Hence details displayed, closing the connection
ERROR:2023-04-05 10:51:31,419:app:Exception on /search/Naruto [GET]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, value)
psycopg2.errors.UndefinedFunction: operator does not exist: details ->> unknown
LINE 1: SELECT * FROM hotel WHERE guest_details ->> 'name' = 'Naruto...
                                                ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 118, in search_guests
    return jsonify({"message": error})
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type UndefinedFunction is not JSON serializable
ERROR:2023-04-05 10:51:31,419:app:Exception on /search/Naruto [GET]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, value)
psycopg2.errors.UndefinedFunction: operator does not exist: details ->> unknown
LINE 1: SELECT * FROM hotel WHERE guest_details ->> 'name' = 'Naruto...
                                                ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 118, in search_guests
    return jsonify({"message": error})
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type UndefinedFunction is not JSON serializable
ERROR:2023-04-05 10:51:31,419:app:Exception on /search/Naruto [GET]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, value)
psycopg2.errors.UndefinedFunction: operator does not exist: details ->> unknown
LINE 1: SELECT * FROM hotel WHERE guest_details ->> 'name' = 'Naruto...
                                                ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 118, in search_guests
    return jsonify({"message": error})
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type UndefinedFunction is not JSON serializable
WARNING:2023-04-05 10:52:24,550:app:Starting the db connection to display all guests in the list
ERROR:2023-04-05 10:52:24,760:app:Error occurred: operator does not exist: details ->> unknown
LINE 1: SELECT * FROM hotel WHERE guest_details ->> 'name' = 'Naruto...
                                                ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, value)
psycopg2.errors.UndefinedFunction: operator does not exist: details ->> unknown
LINE 1: SELECT * FROM hotel WHERE guest_details ->> 'name' = 'Naruto...
                                                ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

ERROR:2023-04-05 10:52:24,760:app:Error occurred: operator does not exist: details ->> unknown
LINE 1: SELECT * FROM hotel WHERE guest_details ->> 'name' = 'Naruto...
                                                ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, value)
psycopg2.errors.UndefinedFunction: operator does not exist: details ->> unknown
LINE 1: SELECT * FROM hotel WHERE guest_details ->> 'name' = 'Naruto...
                                                ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

WARNING:2023-04-05 10:52:24,762:app:Hence details displayed, closing the connection
WARNING:2023-04-05 10:52:24,762:app:Hence details displayed, closing the connection
WARNING:2023-04-05 10:52:24,762:app:Hence details displayed, closing the connection
ERROR:2023-04-05 10:52:24,762:app:Exception on /search/Naruto [GET]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, value)
psycopg2.errors.UndefinedFunction: operator does not exist: details ->> unknown
LINE 1: SELECT * FROM hotel WHERE guest_details ->> 'name' = 'Naruto...
                                                ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 118, in search_guests
    return jsonify({"message": error})
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type UndefinedFunction is not JSON serializable
ERROR:2023-04-05 10:52:24,762:app:Exception on /search/Naruto [GET]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, value)
psycopg2.errors.UndefinedFunction: operator does not exist: details ->> unknown
LINE 1: SELECT * FROM hotel WHERE guest_details ->> 'name' = 'Naruto...
                                                ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 118, in search_guests
    return jsonify({"message": error})
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type UndefinedFunction is not JSON serializable
ERROR:2023-04-05 10:52:24,762:app:Exception on /search/Naruto [GET]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, value)
psycopg2.errors.UndefinedFunction: operator does not exist: details ->> unknown
LINE 1: SELECT * FROM hotel WHERE guest_details ->> 'name' = 'Naruto...
                                                ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 118, in search_guests
    return jsonify({"message": error})
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type UndefinedFunction is not JSON serializable
WARNING:2023-04-05 10:52:46,435:app:Starting the db connection to display all guests in the list
ERROR:2023-04-05 10:52:46,938:app:Error occurred: operator does not exist: details -> unknown
LINE 1: SELECT * FROM hotel WHERE guest_details -> 'name' = 'Naruto'...
                                                ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, value)
psycopg2.errors.UndefinedFunction: operator does not exist: details -> unknown
LINE 1: SELECT * FROM hotel WHERE guest_details -> 'name' = 'Naruto'...
                                                ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

ERROR:2023-04-05 10:52:46,938:app:Error occurred: operator does not exist: details -> unknown
LINE 1: SELECT * FROM hotel WHERE guest_details -> 'name' = 'Naruto'...
                                                ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, value)
psycopg2.errors.UndefinedFunction: operator does not exist: details -> unknown
LINE 1: SELECT * FROM hotel WHERE guest_details -> 'name' = 'Naruto'...
                                                ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

WARNING:2023-04-05 10:52:46,941:app:Hence details displayed, closing the connection
WARNING:2023-04-05 10:52:46,941:app:Hence details displayed, closing the connection
WARNING:2023-04-05 10:52:46,941:app:Hence details displayed, closing the connection
ERROR:2023-04-05 10:52:46,942:app:Exception on /search/Naruto [GET]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, value)
psycopg2.errors.UndefinedFunction: operator does not exist: details -> unknown
LINE 1: SELECT * FROM hotel WHERE guest_details -> 'name' = 'Naruto'...
                                                ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 118, in search_guests
    return jsonify({"message": error})
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type UndefinedFunction is not JSON serializable
ERROR:2023-04-05 10:52:46,942:app:Exception on /search/Naruto [GET]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, value)
psycopg2.errors.UndefinedFunction: operator does not exist: details -> unknown
LINE 1: SELECT * FROM hotel WHERE guest_details -> 'name' = 'Naruto'...
                                                ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 118, in search_guests
    return jsonify({"message": error})
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type UndefinedFunction is not JSON serializable
ERROR:2023-04-05 10:52:46,942:app:Exception on /search/Naruto [GET]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 110, in search_guests
    cur.execute(show_query, value)
psycopg2.errors.UndefinedFunction: operator does not exist: details -> unknown
LINE 1: SELECT * FROM hotel WHERE guest_details -> 'name' = 'Naruto'...
                                                ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 118, in search_guests
    return jsonify({"message": error})
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type UndefinedFunction is not JSON serializable
WARNING:2023-04-05 11:03:38,215:app:Starting the db connection to update booking status of rooms in the list
ERROR:2023-04-05 11:03:38,215:app:Error occurred: tuple index out of range
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 111, in booking_status
    cur.execute(update_query, (status, ))
IndexError: tuple index out of range
ERROR:2023-04-05 11:03:38,215:app:Error occurred: tuple index out of range
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 111, in booking_status
    cur.execute(update_query, (status, ))
IndexError: tuple index out of range
WARNING:2023-04-05 11:03:38,216:app:Hence details displayed, closing the connection
WARNING:2023-04-05 11:03:38,216:app:Hence details displayed, closing the connection
WARNING:2023-04-05 11:03:38,216:app:Hence details displayed, closing the connection
ERROR:2023-04-05 11:03:38,216:app:Exception on /status/101 [PUT]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 111, in booking_status
    cur.execute(update_query, (status, ))
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 118, in booking_status
    return jsonify({"message": error})
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type IndexError is not JSON serializable
ERROR:2023-04-05 11:03:38,216:app:Exception on /status/101 [PUT]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 111, in booking_status
    cur.execute(update_query, (status, ))
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 118, in booking_status
    return jsonify({"message": error})
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type IndexError is not JSON serializable
ERROR:2023-04-05 11:03:38,216:app:Exception on /status/101 [PUT]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 111, in booking_status
    cur.execute(update_query, (status, ))
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 118, in booking_status
    return jsonify({"message": error})
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type IndexError is not JSON serializable
WARNING:2023-04-05 11:04:04,330:app:Starting the db connection to update booking status of rooms in the list
INFO:2023-04-05 11:04:04,537:app:Status updated of room no. 101
INFO:2023-04-05 11:04:04,537:app:Status updated of room no. 101
WARNING:2023-04-05 11:04:04,537:app:Hence details displayed, closing the connection
WARNING:2023-04-05 11:04:04,537:app:Hence details displayed, closing the connection
WARNING:2023-04-05 11:04:04,537:app:Hence details displayed, closing the connection
WARNING:2023-04-05 11:04:30,819:app:Starting the db connection to display all guests in the list
WARNING:2023-04-05 11:04:30,819:app:Starting the db connection to display all guests in the list
WARNING:2023-04-05 11:04:30,819:app:Starting the db connection to display all guests in the list
WARNING:2023-04-05 11:04:30,819:app:Starting the db connection to display all guests in the list
INFO:2023-04-05 11:04:31,021:app:Displayed list of all guests in the list
INFO:2023-04-05 11:04:31,021:app:Displayed list of all guests in the list
INFO:2023-04-05 11:04:31,021:app:Displayed list of all guests in the list
INFO:2023-04-05 11:04:31,021:app:Displayed list of all guests in the list
INFO:2023-04-05 11:04:31,021:app:Displayed list of all guests in the list
WARNING:2023-04-05 11:04:31,022:app:Hence details displayed, closing the connection
WARNING:2023-04-05 11:04:31,022:app:Hence details displayed, closing the connection
WARNING:2023-04-05 11:04:31,022:app:Hence details displayed, closing the connection
WARNING:2023-04-05 11:04:31,022:app:Hence details displayed, closing the connection
WARNING:2023-04-05 11:04:31,022:app:Hence details displayed, closing the connection
WARNING:2023-04-05 11:04:31,022:app:Hence details displayed, closing the connection
WARNING:2023-04-05 12:42:16,575:app:Starting the db connection to display all guests in the list
INFO:2023-04-05 12:42:16,826:app:Displayed list of all guests in the list
INFO:2023-04-05 12:42:16,826:app:Displayed list of all guests in the list
WARNING:2023-04-05 12:42:16,828:app:Closing the connection
WARNING:2023-04-05 12:42:16,828:app:Closing the connection
WARNING:2023-04-05 12:42:16,828:app:Closing the connection
WARNING:2023-04-14 13:50:47,003:app:Starting the db connection to add guests in room_id in the rooms table
WARNING:2023-04-14 13:50:47,004:settings:Hence account created, closing the connection
ERROR:2023-04-14 13:50:47,004:app:Exception on /rooms [POST]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/settings.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 88, in add_room_details
    cur.execute(add_query, values)
TypeError: not all arguments converted during string formatting

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/settings.py", line 32, in wrapper
    except psycopg2.Error as error:
NameError: name 'psycopg2' is not defined
WARNING:2023-04-14 13:54:07,709:app:Starting the db connection to add guests in room_id in the rooms table
WARNING:2023-04-14 13:54:07,709:app:Starting the db connection to add guests in room_id in the rooms table
WARNING:2023-04-14 13:54:07,710:settings:Hence account created, closing the connection
WARNING:2023-04-14 13:54:07,710:settings:Hence account created, closing the connection
ERROR:2023-04-14 13:54:07,710:app:Exception on /rooms [POST]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/settings.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 88, in add_room_details
    cur.execute(add_query, values)
TypeError: not all arguments converted during string formatting

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/settings.py", line 32, in wrapper
    except psycopg2.Error as error:
NameError: name 'psycopg2' is not defined
ERROR:2023-04-14 13:54:07,710:app:Exception on /rooms [POST]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/settings.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 88, in add_room_details
    cur.execute(add_query, values)
TypeError: not all arguments converted during string formatting

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/settings.py", line 32, in wrapper
    except psycopg2.Error as error:
NameError: name 'psycopg2' is not defined
WARNING:2023-04-14 13:54:19,174:app:Starting the db connection to add guests in room_id in the rooms table
WARNING:2023-04-14 13:54:19,466:settings:Hence account created, closing the connection
ERROR:2023-04-14 13:54:19,467:app:Exception on /rooms [POST]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/settings.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 88, in add_room_details
    cur.execute(add_query, values)
psycopg2.errors.UndefinedColumn: column "guest_id" of relation "hotel" does not exist
LINE 1: INSERT INTO hotel(room_id, guest_id, room_type, status)VALUE...
                                   ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/settings.py", line 32, in wrapper
    except psycopg2.Error as error:
NameError: name 'psycopg2' is not defined
WARNING:2023-04-14 15:00:59,125:app:Starting the db connection to add guests in room_id in the rooms table
WARNING:2023-04-14 15:00:59,998:settings:Hence account created, closing the connection
ERROR:2023-04-14 15:00:59,998:app:Exception on /rooms [POST]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/settings.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 88, in add_room_details
    cur.execute(add_query, values)
psycopg2.errors.UndefinedColumn: column "guest_id" of relation "hotel" does not exist
LINE 1: INSERT INTO hotel(room_id, guest_id, room_type, status)VALUE...
                                   ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/settings.py", line 32, in wrapper
    except psycopg2.Error as error:
NameError: name 'psycopg2' is not defined
WARNING:2023-04-14 15:01:38,260:app:Starting the db connection to add guests in room_id in the rooms table
INFO:2023-04-14 15:01:38,626:app:Guest with id 1 has been shifted to room id 101
INFO:2023-04-14 15:01:38,626:app:Guest with id 1 has been shifted to room id 101
WARNING:2023-04-14 15:01:38,626:settings:Hence account created, closing the connection
WARNING:2023-04-14 15:02:17,186:app:Starting the db connection to add guests in room_id in the rooms table
WARNING:2023-04-14 15:02:17,186:app:Starting the db connection to add guests in room_id in the rooms table
WARNING:2023-04-14 15:02:17,186:app:Starting the db connection to add guests in room_id in the rooms table
INFO:2023-04-14 15:02:17,454:app:Guest with id 2 has been shifted to room id 102
INFO:2023-04-14 15:02:17,454:app:Guest with id 2 has been shifted to room id 102
INFO:2023-04-14 15:02:17,454:app:Guest with id 2 has been shifted to room id 102
INFO:2023-04-14 15:02:17,454:app:Guest with id 2 has been shifted to room id 102
WARNING:2023-04-14 15:02:17,455:settings:Hence account created, closing the connection
WARNING:2023-04-14 15:02:17,455:settings:Hence account created, closing the connection
WARNING:2023-04-14 15:02:42,830:app:Starting the db connection to add guests in room_id in the rooms table
WARNING:2023-04-14 15:02:42,830:app:Starting the db connection to add guests in room_id in the rooms table
WARNING:2023-04-14 15:02:42,830:app:Starting the db connection to add guests in room_id in the rooms table
WARNING:2023-04-14 15:02:42,830:app:Starting the db connection to add guests in room_id in the rooms table
WARNING:2023-04-14 15:02:42,830:app:Starting the db connection to add guests in room_id in the rooms table
INFO:2023-04-14 15:02:43,245:app:Guest with id 3 has been shifted to room id 103
INFO:2023-04-14 15:02:43,245:app:Guest with id 3 has been shifted to room id 103
INFO:2023-04-14 15:02:43,245:app:Guest with id 3 has been shifted to room id 103
INFO:2023-04-14 15:02:43,245:app:Guest with id 3 has been shifted to room id 103
INFO:2023-04-14 15:02:43,245:app:Guest with id 3 has been shifted to room id 103
INFO:2023-04-14 15:02:43,245:app:Guest with id 3 has been shifted to room id 103
WARNING:2023-04-14 15:02:43,246:settings:Hence account created, closing the connection
WARNING:2023-04-14 15:02:43,246:settings:Hence account created, closing the connection
WARNING:2023-04-14 15:02:43,246:settings:Hence account created, closing the connection
WARNING:2023-04-14 15:18:07,783:app:Starting the db connection to display all guests in the list
INFO:2023-04-14 15:18:08,397:app:Displayed list of all guests in the list
INFO:2023-04-14 15:18:08,397:app:Displayed list of all guests in the list
WARNING:2023-04-14 15:18:08,398:settings:Hence account created, closing the connection
WARNING:2023-04-14 15:18:21,789:app:Starting the db connection to display all guests in the list
WARNING:2023-04-14 15:18:21,789:app:Starting the db connection to display all guests in the list
WARNING:2023-04-14 15:18:21,789:app:Starting the db connection to display all guests in the list
INFO:2023-04-14 15:18:21,957:app:Displayed list of all guests in the list
INFO:2023-04-14 15:18:21,957:app:Displayed list of all guests in the list
INFO:2023-04-14 15:18:21,957:app:Displayed list of all guests in the list
INFO:2023-04-14 15:18:21,957:app:Displayed list of all guests in the list
WARNING:2023-04-14 15:18:21,958:settings:Hence account created, closing the connection
WARNING:2023-04-14 15:18:21,958:settings:Hence account created, closing the connection
WARNING:2023-04-14 15:20:12,037:app:Starting the db connection to update the details 
WARNING:2023-04-14 15:20:12,037:app:Starting the db connection to update the details 
WARNING:2023-04-14 15:20:12,037:app:Starting the db connection to update the details 
WARNING:2023-04-14 15:20:12,037:app:Starting the db connection to update the details 
WARNING:2023-04-14 15:20:12,037:app:Starting the db connection to update the details 
WARNING:2023-04-14 15:20:12,037:settings:Hence account created, closing the connection
WARNING:2023-04-14 15:20:12,037:settings:Hence account created, closing the connection
WARNING:2023-04-14 15:20:12,037:settings:Hence account created, closing the connection
ERROR:2023-04-14 15:20:12,038:app:Exception on /rooms/1 [PUT]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/settings.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 220, in update_room_details
    cur.execute("SELECT * from rooms where room_id = %s", (id,))
psycopg2.ProgrammingError: can't adapt type 'builtin_function_or_method'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/settings.py", line 32, in wrapper
    except psycopg2.Error as error:
NameError: name 'psycopg2' is not defined
ERROR:2023-04-14 15:20:12,038:app:Exception on /rooms/1 [PUT]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/settings.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 220, in update_room_details
    cur.execute("SELECT * from rooms where room_id = %s", (id,))
psycopg2.ProgrammingError: can't adapt type 'builtin_function_or_method'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/settings.py", line 32, in wrapper
    except psycopg2.Error as error:
NameError: name 'psycopg2' is not defined
ERROR:2023-04-14 15:20:12,038:app:Exception on /rooms/1 [PUT]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/settings.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 220, in update_room_details
    cur.execute("SELECT * from rooms where room_id = %s", (id,))
psycopg2.ProgrammingError: can't adapt type 'builtin_function_or_method'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/settings.py", line 32, in wrapper
    except psycopg2.Error as error:
NameError: name 'psycopg2' is not defined
ERROR:2023-04-14 15:20:12,038:app:Exception on /rooms/1 [PUT]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/settings.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 220, in update_room_details
    cur.execute("SELECT * from rooms where room_id = %s", (id,))
psycopg2.ProgrammingError: can't adapt type 'builtin_function_or_method'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/settings.py", line 32, in wrapper
    except psycopg2.Error as error:
NameError: name 'psycopg2' is not defined
ERROR:2023-04-14 15:20:12,038:app:Exception on /rooms/1 [PUT]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/settings.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 220, in update_room_details
    cur.execute("SELECT * from rooms where room_id = %s", (id,))
psycopg2.ProgrammingError: can't adapt type 'builtin_function_or_method'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/settings.py", line 32, in wrapper
    except psycopg2.Error as error:
NameError: name 'psycopg2' is not defined
WARNING:2023-04-14 15:21:14,275:app:Starting the db connection to update the details 
WARNING:2023-04-14 15:21:14,486:settings:Hence account created, closing the connection
WARNING:2023-04-14 15:22:23,297:app:Starting the db connection to update the details 
WARNING:2023-04-14 15:22:23,518:settings:Hence account created, closing the connection
WARNING:2023-04-14 15:24:26,695:app:Starting the db connection to update the details 
WARNING:2023-04-14 15:24:27,012:settings:Hence account created, closing the connection
WARNING:2023-04-14 15:25:10,262:app:Starting the db connection to update the details 
WARNING:2023-04-14 15:25:11,009:settings:Hence account created, closing the connection
WARNING:2023-04-14 15:25:46,565:app:Starting the db connection to update the details 
WARNING:2023-04-14 15:25:47,179:settings:Hence account created, closing the connection
WARNING:2023-04-14 15:25:55,738:app:Starting the db connection to update the details 
WARNING:2023-04-14 15:25:55,738:app:Starting the db connection to update the details 
WARNING:2023-04-14 15:25:56,108:settings:Hence account created, closing the connection
WARNING:2023-04-14 15:25:56,108:settings:Hence account created, closing the connection
WARNING:2023-04-14 15:26:31,474:app:Starting the db connection to update the details 
WARNING:2023-04-14 15:26:31,749:settings:Hence account created, closing the connection
ERROR:2023-04-14 15:26:31,750:app:Exception on /rooms/101 [PUT]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/settings.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 237, in update_room_details
    cur.execute("UPDATE rooms SET room_type = %s WHERE id = %s", (room_type, id))
psycopg2.ProgrammingError: can't adapt type 'builtin_function_or_method'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/settings.py", line 32, in wrapper
    except psycopg2.Error as error:
NameError: name 'psycopg2' is not defined
WARNING:2023-04-14 15:27:30,653:app:Starting the db connection to update the details 
WARNING:2023-04-14 15:27:31,105:settings:Hence account created, closing the connection
ERROR:2023-04-14 15:27:31,105:app:Exception on /rooms/101 [PUT]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/settings.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/app.py", line 237, in update_room_details
    cur.execute("UPDATE rooms SET room_type = %s WHERE id = %s", (room_type, room_id))
psycopg2.errors.UndefinedColumn: column "id" does not exist
LINE 1: UPDATE rooms SET room_type = 'triple' WHERE id = 101
                                                    ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hotel/settings.py", line 32, in wrapper
    except psycopg2.Error as error:
NameError: name 'psycopg2' is not defined
WARNING:2023-04-14 15:27:55,535:app:Starting the db connection to update the details 
INFO:2023-04-14 15:27:56,926:app:Details updated: {'room_type': 'triple', 'status': 'cleaning done'}
INFO:2023-04-14 15:27:56,926:app:Details updated: {'room_type': 'triple', 'status': 'cleaning done'}
WARNING:2023-04-14 15:27:56,927:settings:Hence account created, closing the connection
WARNING:2023-04-14 15:37:05,656:app:Starting the db connection to update the details 
INFO:2023-04-14 15:37:06,020:app:Details updated: {'room_type': 'triple', 'status': 'cleaning done'}
INFO:2023-04-14 15:37:06,020:app:Details updated: {'room_type': 'triple', 'status': 'cleaning done'}
WARNING:2023-04-14 15:37:06,021:settings:Hence account created, closing the connection
WARNING:2023-04-14 15:37:34,308:app:Starting the db connection to update the details 
INFO:2023-04-14 15:37:35,580:app:Details updated: {'room_type': 'triple', 'status': 'cleaning done'}
INFO:2023-04-14 15:37:35,580:app:Details updated: {'room_type': 'triple', 'status': 'cleaning done'}
WARNING:2023-04-14 15:37:35,581:settings:Hence account created, closing the connection
WARNING:2023-04-14 15:39:12,470:app:Starting the db connection to update the details 
WARNING:2023-04-14 15:39:12,470:app:Starting the db connection to update the details 
WARNING:2023-04-14 15:39:12,470:app:Starting the db connection to update the details 
INFO:2023-04-14 15:39:13,150:app:Details updated: {'room_type': 'double', 'status': 'cleaning done'}
INFO:2023-04-14 15:39:13,150:app:Details updated: {'room_type': 'double', 'status': 'cleaning done'}
INFO:2023-04-14 15:39:13,150:app:Details updated: {'room_type': 'double', 'status': 'cleaning done'}
INFO:2023-04-14 15:39:13,150:app:Details updated: {'room_type': 'double', 'status': 'cleaning done'}
WARNING:2023-04-14 15:39:13,150:settings:Hence account created, closing the connection
WARNING:2023-04-14 15:39:13,150:settings:Hence account created, closing the connection
WARNING:2023-04-14 15:41:25,478:app:Starting the db connection to update the details 
WARNING:2023-04-14 15:41:25,478:app:Starting the db connection to update the details 
WARNING:2023-04-14 15:41:25,478:app:Starting the db connection to update the details 
WARNING:2023-04-14 15:41:25,478:app:Starting the db connection to update the details 
WARNING:2023-04-14 15:41:25,478:app:Starting the db connection to update the details 
INFO:2023-04-14 15:41:27,251:app:Details updated: {'room_type': 'double', 'status': 'cleaning'}
INFO:2023-04-14 15:41:27,251:app:Details updated: {'room_type': 'double', 'status': 'cleaning'}
INFO:2023-04-14 15:41:27,251:app:Details updated: {'room_type': 'double', 'status': 'cleaning'}
INFO:2023-04-14 15:41:27,251:app:Details updated: {'room_type': 'double', 'status': 'cleaning'}
INFO:2023-04-14 15:41:27,251:app:Details updated: {'room_type': 'double', 'status': 'cleaning'}
INFO:2023-04-14 15:41:27,251:app:Details updated: {'room_type': 'double', 'status': 'cleaning'}
WARNING:2023-04-14 15:41:27,252:settings:Hence account created, closing the connection
WARNING:2023-04-14 15:41:27,252:settings:Hence account created, closing the connection
WARNING:2023-04-14 15:41:27,252:settings:Hence account created, closing the connection
WARNING:2023-04-14 15:43:23,026:app:Starting the db connection to update the details 
INFO:2023-04-14 15:43:25,040:app:Details updated: {'room_type': 'double', 'status': 'cleaning'}
INFO:2023-04-14 15:43:25,040:app:Details updated: {'room_type': 'double', 'status': 'cleaning'}
WARNING:2023-04-14 15:43:25,041:settings:Hence account created, closing the connection
WARNING:2023-04-14 15:45:05,676:app:Starting the db connection to update the details 
INFO:2023-04-14 15:45:07,031:app:Details updated: {'room_type': 'double', 'status': 'cleaning'}
INFO:2023-04-14 15:45:07,031:app:Details updated: {'room_type': 'double', 'status': 'cleaning'}
WARNING:2023-04-14 15:45:07,032:settings:Hence account created, closing the connection
WARNING:2023-04-14 15:46:08,507:app:Starting the db connection to update the details 
INFO:2023-04-14 15:46:08,892:app:Details updated: {'room_type': 'double', 'status': 'cleaning'}
INFO:2023-04-14 15:46:08,892:app:Details updated: {'room_type': 'double', 'status': 'cleaning'}
WARNING:2023-04-14 15:46:08,893:settings:Hence account created, closing the connection
